### ISSUE TITLE
I would like to ask if the image for the header was created using a template or generated online?

### ISSUE THREAD

**Issue by xJoyLu** [jktrn/astro-erudite#3]
I saw your theme at astro and liked it enough to deploy it right away.

However, the article title image specifies a fixed format, and I see that you have generated similar 2023, 2024 , and would like to ask by what means?

Deployment URL: blog.ldd.cc

**Comment by jktrn** [comment]
Hello @xJoyLu!

The article title image specifies a fixed format because typically, meta images are 1200x630! This is Facebook's standard. The names I specified are arbitrary and can be named whatever, I just named them 2023 and 2024 since they made sense. If you're curious, I made them using Figma (not via generation).

**Comment by xJoyLu** [comment]
Just figure out the reason. Figma is really great.
